/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomInfo: typeof import('./src/components/bottomInfo/bottomInfo.vue')['default']
    Charts: typeof import('./src/components/charts/index.vue')['default']
    CommandMenu: typeof import('./src/components/commandMenu/index.vue')['default']
    Common: typeof import('./src/components/upload/common.vue')['default']
    CustomPic: typeof import('./src/components/customPic/index.vue')['default']
    Docx: typeof import('./src/components/office/docx.vue')['default']
    Excel: typeof import('./src/components/office/excel.vue')['default']
    ExportExcel: typeof import('./src/components/exportExcel/exportExcel.vue')['default']
    ExportTemplate: typeof import('./src/components/exportExcel/exportTemplate.vue')['default']
    Image: typeof import('./src/components/upload/image.vue')['default']
    ImportExcel: typeof import('./src/components/exportExcel/importExcel.vue')['default']
    Office: typeof import('./src/components/office/index.vue')['default']
    Pdf: typeof import('./src/components/office/pdf.vue')['default']
    RichEdit: typeof import('./src/components/richtext/rich-edit.vue')['default']
    RichView: typeof import('./src/components/richtext/rich-view.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectComponent: typeof import('./src/components/selectImage/selectComponent.vue')['default']
    SelectFile: typeof import('./src/components/selectFile/selectFile.vue')['default']
    SelectImage: typeof import('./src/components/selectImage/selectImage.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon/svgIcon.vue')['default']
    WarningBar: typeof import('./src/components/warningBar/warningBar.vue')['default']
  }
}
